// ERRORS
export const EMPTY_ERRORS = 'EMPTY_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

// ADMIN
export const BEFORE_ADMIN = 'BEFORE_ADMIN';
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const GET_ADMIN = 'GET_ADMIN';
export const CREATE_ADMIN = 'CREATE_ADMIN';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const LIST_ADMIN = 'LIST_ADMIN';

// PRIVATE ADMIN
export const CREATE_PRIVATE_ADMIN = 'CREATE_PRIVATE_ADMIN';


// Dashboard-data
 export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
 
// Members
export const CREATE_MEMBER = "CREATE_MEMBER";
export const BEFORE_MEMBER = "BEFORE_MEMBER";
export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBER = "GET_MEMBER";
export const UPSERT_MEMBER = "UPSERT_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";

// COACHES
export const CREATE_COACH = "CREATE_COACH";
export const BEFORE_COACH = "BEFORE_COACH";
export const GET_COACH = "GET_COACH";
export const UPDATE_COACH = "UPDATE_COACH";
export const EDIT_COACH = "EDIT_COACH";
export const DELETE_COACH = "DELETE_COACH";
export const LIST_COACH = 'LIST_COACH';

// COACH SCHEDULAR
export const CREATE_SCHEDULAR = "CREATE_SCHEDULAR";
export const BEFORE_SCHEDULAR = "BEFORE_SCHEDULAR";
export const SCHEDULAR_LIST = "SCHEDULAR_LIST";
export const GET_SCHEDULAR = "GET_SCHEDULAR";
export const UPDATE_SCHEDULAR = "UPDATE_SCHEDULAR";


// Services
export const CREATE_SERVICES = 'CREATE_SERVICES';
export const BEFORE_SERVICES = 'BEFORE_SERVICES';
export const LIST_SERVICES = 'LIST_SERVICES';
export const GET_SERVICE = 'GET_SERVICE';
export const UPDATE_SERVICES = 'UPDATE_SERVICES';
export const DELETE_SERVICES = 'DELETE_SERVICES';

// CMS
export const BEFORE_CMS = 'BEFORE_CMS';
export const CREATE_CMS = 'CREATE_CMS';
export const CMS_LIST = 'CMS_LIST';
export const GET_CMS = 'GET_CMS';
export const UPDATE_CMS = "UPDATE_CMS";
export const DELETE_CMS = 'DELETE_CMS';

// REVIEW
export const BEFORE_REVIEW = 'BEFORE_REVIEW';
export const REVIEW_LIST = 'REVIEW_LIST';
export const GET_REVIEW = 'GET_REVIEW';
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = 'DELETE_REVIEW';
//Membership
export const BEFORE_MEMBERSHIP = 'BEFORE_MEMBERSHIP';
export const CREATE_MEMBERSHIP = 'CREATE_MEMBERSHIP';
export const MEMBERSHIP_LIST = 'MEMBERSHIP_LIST';
export const GET_MEMBERSHIP = 'GET_MEMBERSHIP';
export const UPDATE_MEMBERSHIP = 'UPDATE_MEMBERSHIP';
export const DELETE_MEMBERSHIP = 'DELETE_MEMBERSHIP';

//COACHMEMBERSHIP
export const BEFORE_COACHMEMBERSHIP = 'BEFORE_COACHMEMBERSHIP';
export const CREATE_COACHMEMBERSHIP = 'CREATE_COACHMEMBERSHIP';
export const COACHMEMBERSHIP_LIST = 'COACHMEMBERSHIP_LIST';
export const GET_COACHMEMBERSHIP = 'GET_COACHMEMBERSHIP';
export const UPDATE_COACHMEMBERSHIP = 'UPDATE_COACHMEMBERSHIP';
export const DELETE_COACHMEMBERSHIP = 'DELETE_COACHMEMBERSHIP';

// UserMemberships
export const USERMEMBERSHIP_LIST = 'USERMEMBERSHIP_LIST';
export const GET_USERMEMBERSHIP = 'GET_USERMEMBERSHIP';
export const BEFORE_USERMEMBERSHIP = 'BEFORE_USERMEMBERSHIP';
export const UPDATE_USERMEMBERSHIP = 'UPDATE_USERMEMBERSHIP';

// CoachMembership Record
export const COACHRECORD_LIST = 'COACHRECORD_LIST';
export const GET_COACHRECORD = 'GET_COACHRECORD';
export const BEFORE_COACHRECORD = 'BEFORE_COACHRECORD';
export const UPDATE_COACHRECORD = 'UPDATE_COACHRECORD';
// Emails
export const GET_EMAILS = 'GET_EMAILS';
export const GET_EMAIL = 'GET_EMAIL';
export const BEFORE_EMAIL = 'BEFORE_EMAIL';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const DELETE_EMAIL = 'DELETE_EMAIL';

// Settings
export const GET_SETTINGS = 'GET_SETTINGS';
export const EDIT_SETTINGS = 'EDIT_SETTINGS';
export const BEFORE_SETTINGS = 'BEFORE_SETTINGS';

// CONTACTS
export const BEFORE_CONTACT = 'BEFORE_CONTACT';
export const GET_CONTACTS = 'GET_CONTACTS';
export const EDIT_CONTACT = 'EDIT_CONTACT';

//Permissions
export const BEFORE_PERMISSION = 'BEFORE_PERMISSION';
export const CREATE_PERMISSION = 'CREATE_PERMISSION';
export const GET_PERMISSION = 'GET_PERMISSION';
export const UPDATE_PERMISSION = 'UPDATE_PERMISSION';
export const DELETE_PERMISSION = 'DELETE_PERMISSION';

// BLOGS
export const BEFORE_BLOG = 'BEFORE_BLOG';
export const CREATE_BLOG = 'CREATE_BLOG';
export const BLOG_LIST = 'BLOG_LIST';
export const GET_BLOG = 'GET_BLOG';
export const UPDATE_BLOG = "UPDATE_BLOG";
export const DELETE_BLOG = 'DELETE_BLOG';

// BLOGCATEGORIES
export const BEFORE_CATEGORY = 'BEFORE_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const LIST_CATEGORY = 'LIST_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
