const express = require('express')
const adminRoutes = require('./admin.route')
const dashboardRoute = require('./dashboard.route')
const memberRoutes = require('./members.route')
const cmsRoutes = require('./cms.route')
const reviewRoutes = require('./review.route')
const emailRoutes = require('./email.route')
const contactRoutes = require('./contact.route')
const permissionsRoutes = require('./permissions.route')
const membermembershipRoutes = require('./membermembership.route')
const coachmembershipRoutes = require('./coachmembership.route')
const coachesRoutes = require('./coaches.route')
const userMembershipRoutes = require('./usermembership.route');
const coachSchedularRoutes = require('./coachSchedular.route')
const servicesRoutes = require('./services.route')
const coachRecordRoutes = require('./coachRecord.route')
const blogsRoutes = require('./blog.route')
const catagoryRoutes = require('./catagory.route')
const settingsRoutes = require('./settings.route')
const router = express.Router()
/**
 * GET v1/admin
 */
router.use('/staff', adminRoutes)
router.use('/dashboard', dashboardRoute)
router.use('/user', memberRoutes)
router.use('/coach', coachesRoutes )
router.use('/cms', cmsRoutes)
router.use('/review', reviewRoutes)
router.use('/email', emailRoutes)
router.use('/contacts', contactRoutes)
router.use('/permissions',permissionsRoutes)
router.use('/membermembership', membermembershipRoutes)
router.use('/coachmembership', coachmembershipRoutes)
router.use('/coachrecord', coachRecordRoutes)
router.use('/usermembership', userMembershipRoutes)
router.use('/schedular', coachSchedularRoutes)
router.use('/services', servicesRoutes)
router.use('/blog', blogsRoutes)
router.use('/catagory', catagoryRoutes)
router.use('/settings', settingsRoutes)

module.exports = router
