
module.exports = function getHtml() {
    const templatePayload = {
    type:"forgot-password",
    subject:"forgot-password",
    text:"<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n\t<meta charset=\"UTF-8\">\n\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\t<title>Document</title>\n</head>\n\n<body style=\"margin:0;\">\n\t<div style=\"max-width:600px;margin:auto;background:#f9f9f9;color:#222;font-size:17px\">\n\t\t<div style=\"padding:0 30px;font-family:Segoe,Segoe UI,sans-serif\">\n\t\t\t<h3 style=\"font-size:22px;text-transform:capitalize;font-family:Segoe,Segoe UI,sans-serif;margin-top:20px\">\n\t\t\t\tDear <span style=\"color:#025a99\">User</span>\n\t\t\t</h3>\n\t\t\t<div style=\"font-size:18px;line-height:25px;margin-bottom:30px\">\n\t\t\t\t<p>There has been a request to reset your password. Please click the button below to reset password:</p>\n\t\t\t</div>\n\t\t\t<div style=\"font-size:18px;line-height:25px;margin-bottom:30px\">\n\t\t\t\t<a href=\"${url}\" style=\"background:linear-gradient(to bottom,  #025a99 0%,#025a99 17%,#024f85 66%,#004c7e 77%,#024677 100%);border:1px solid #025a99;font-size: 16px;\n\t\t\t\t\tline-height: 19px;\n\t\t\t\t\tfont-weight: bold;\n\t\t\t\t\tcolor: #fff;text-align:center;text-decoration: none;\n\t\t\t\t\tpadding: 12px 17px;border-radius:4px;\">Reset Password</a>\n\t\t\t\t<p>If you didn’t mean to reset your password, then you can just ignore this email, your password will\n\t\t\t\t\tnot be changed.\n\t\t\t\t</p>\n\t\t\t</div>\n\t\t\t<div style=\"font-size:18px;line-height:25px;margin-bottom:30px\">\n\t\t\t\t<p>Thank you for being a part of <strong style=\"color:#025a99\">HealthiWealthi</strong>!</p>\n\t\t\t</div>\n\t\t\t<div\n\t\t\t\tstyle=\"padding-top:30px;margin:0 0 50px;font-family:Segoe,Segoe UI,sans-serif;font-size:15px;color:#000000;\">\n\t\t\t\t<p style=\"font-weight:bold;margin:0 0 5px\">Regards,</p>\n\t\t\t\t<p style=\"margin:0 0 5px;\">Team HealthiWealthi</p>\n\t\t\t</div>\n\t\t\t<div\n\t\t\t\tstyle=\"font-family:Segoe,Segoe UI,sans-serif;font-size:12px;line-height:12px;color:#777;text-align:center;background:#f3f3f3;padding:10px 20px 10px\">\n\t\t\t\t<p style=\"margin:0\">Please check out <a style=\"color:#025a99;\" href=\"\"\n\t\t\t\t\t\ttarget=\"_blank\">FAQs</a> section in our website for further assistance.</p>\n\t\t\t</div>\n\t\t\t<div\n\t\t\t\tstyle=\"background:#025a99;padding:10px 20px 10px;font-size:12px;color:#fff;text-align:center;font-family:Segoe,Segoe UI,sans-serif;\">\n\t\t\t\t<p style=\"margin:0;\">Copyright © 2022 <a style=\"color:#fff;\" href=\"\"\n\t\t\t\t\t\ttarget=\"_blank\">HealthiWealthi</a>. All Rights Reserved.</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</body>\n\n</html>"
    }
    return templatePayload;
}
